### ISSUE TITLE
How to get games details of specific year?

### ISSUE THREAD

**Issue by idohi** [seemethere/nba_py#127]
I am trying to get all games details in a specific year. The classes in "nba_py.game" module required  "game_id", but I need details about all the games. Help will be greatly appreciated.

**Comment by KnifeyMoloko** [comment]
I'm actually doing a similar thing right now, so here's what I found:

- Don't start with **nba_py.game**. You'll want to use this module once you have the game ids for the year/season already.
- The **nba_py.teams** module has **TeamGameLogs** class that should return basic records for all of the games in a given season for a given team.

The way I go about this is:

(1) Get team ids from **nba_py.TeamList** and filter out the ones that are no longer active (the list there will contain historical NBA teams too).
(2) loop through team ids returned from (1) with **nba_py.teams.TeamGameLogs** to get the game details, e.g:
`nba_py.teams.TeamGameLogs("1610612749", "2017-18").json`
will get you games from 2017-18 for Milwaukee.
(3) You can use the games details from (2) to make further calls to **nba_py.games**, since you will have all the game ids you need.

BUT, there is a pretty big caveat here: **nba_py.teams.TeamGameLogs**, at least for me, doesn't work very well. It returns a max. of 9 team's data at a time and then just hangs and timeouts. This might be just the nba.com server deciding I'm pulling to much data or just the very basic way the HTML GET request has been set up in nba_py. Either way, for me, getting the full data is gets a bit ugly. An alternative way is to loop over dates for the whole season and make calls to the **Scoreboard** module, as that will also get you game ids. Both methods are far from optimal, but you can get all the games in the end. It's just not a very pretty process.

**Comment by idohi** [comment]
I tried to extract teams with `nba_py.team.TeamList()`  but some how it is stuck (request-cache is installed).

**Comment by KnifeyMoloko** [comment]
> I tried to extract teams with `nba_py.team.TeamList()` but some how it is stuck (request-cache is installed).

Are you able to get data from other nba_py modules?

**Comment by idohi** [comment]
Following 2 examples: one when I get the data and the other when I don't.
[When I get data]
`from nba_py.constants import TEAMS` 
`team_id = TEAMS['ATL']['id']` 
(team_id: '1610612737')

[When I don't get data]
`from nba_py.player import get_player`
`player_id = get_player('Lebron', 'James')`

Maybe its a memory issue, maybe I don't use **requests-cache** properly.

**Comment by idohi** [comment]
It works! Thanks for the assist. 
I installed the package following the instructions in the link you have sent with a small change. (https://www.slothparadise.com/nba_py-documentation/)
1. git clone https://github.com/seemethere/nba_py
2. cd **nba_py-master**
3. `pip install .`

Now, the package is working properly.
