### ISSUE TITLE
Advanced Stats

### ISSUE THREAD

**Issue by arjitj2** [seemethere/nba_py#44]
Hey, is there any way to access the stats found [here](http://stats.nba.com/player/#!/2754/stats/advanced/)?

If not, I'll have to go parse the HTML at basketball reference :/

**Comment by nickb1080** [comment]
This route seems to 403 if you use an HTTP client to try to access it. Unknown how NBA.com tells this apart from browser requests. If you look in the network tab when you load that page, then right click on the request and click "Copy as cURL" (in Chrome), you can paste that into your terminal (even if you omit the cookies!) and get an actual response. However when setting all those headers correctly and using a programmatic HTTP client (he's tried here with Python, I have the same problems with Node) it always 403s. 

I haven't been able to figure out how NBA identifies these requests, but some combined effort on this would be great because if they start using the same strategy across other endpoints all these NBA API clients will be useless.

**Comment by seemethere** [comment]
Yeah it seems that the NBA is getting more aware of things like mine and @nickb1080's projects. If we hope to get this going we're probably going to have to look through their custom code to see what types of things they are setting up before they make the outbound calls to their API.

I just pulled out that custom code and put it in a gist [here](https://gist.github.com/seemethere/4b7591a8a51db8d99c30a82280fc7f9a)

**Comment by arjitj2** [comment]
@nickb1080 that explains it...I tried hitting it with urllib2 and was wondering why none of the stats were coming in.

**Comment by kpascual** [comment]
Hey there, just playing around with this. I'm not sure there's anything funny happening with headers. It might be weirdness with the urllib2/requests libraries, or something environment-related.

For example, doing a basic cURL without custom headers gives you an error:

    curl http://stats.nba.com/stats/boxscoretraditionalv2?EndPeriod=10&EndRange=28800&GameID=0041500406&RangeType=0&Season=2015-16&SeasonType=Playoffs&StartPeriod=1&StartRange=0

But wrapping that URL with quotes doesn't:

    curl 'http://stats.nba.com/stats/boxscoretraditionalv2?EndPeriod=10&EndRange=28800&GameID=0041500406&RangeType=0&Season=2015-16&SeasonType=Playoffs&StartPeriod=1&StartRange=0'

I had the similar errors utilizing urllib2, so I tried using pycurl instead, and that worked fine: https://gist.github.com/kpascual/5e2861c9c8fc80f62ea3872808a08b22

So then I tried using urllib3, and that too worked fine. https://gist.github.com/kpascual/761a47cd058d2e20685e1c76152eb30b

I've validated this on two separate machines, but please let me know if either solution doesn't work for you.

I don't know *why* the other ways throw errors, but honestly I don't care at this point.

**Comment by nickb1080** [comment]
@kpascual huh, interesting! In fact, now when I'm trying that endpoint it works, both in curl -- with AND without the quote -- and also works with [request](https://github.com/request/request) under Node.js. Not sure what to make of this. It certainly didn't work a few weeks back. Seems like something has changed on NBA's side

**Comment by mcdallas** [comment]
The problem seems to be solved if you add the Referer: http://stats.nba.com/player/ into the request headers.

**Comment by mcdallas** [comment]
I sent #45 which allows the endpoint mentioned as well as several others to be accessed.

**Comment by seemethere** [comment]
Closed by #45
