### ISSUE TITLE
Slow response when running code

### ISSUE THREAD

**Issue by vlinsane** [seemethere/nba_py#78]
I'm new to Python so not sure if I'm doing something wrong, but it takes more than two minutes to get any response when running this code:

from nba_py import game
box = game.Boxscore('0041400122')

It that normal? I've tried multiple IDEs with the same code with the same results. My internet is not slow (I have Webpass) either. 

When I try the following in my browser it loads quickly (less than 1 sec):

http://stats.nba.com/stats/boxscoretraditionalv2?StartRange=0&GameID=0041400122&EndPeriod=0&RangeType=0&Season=2016-17&StartPeriod=0&SeasonType=Regular+Season&EndRange=0

Are there any settings I can check?

**Comment by amsimon** [comment]
+1
I'm getting slower responses as of last week. I tried using Ruby's HTTP.get and am still experiencing slower (at least 5x) responses. 

I wonder if nba.stats is throttling requests?

**Comment by gyerli** [comment]
I think they capped each request to 10 secs no matter which measure you are pulling. I also believe that this is just the beggining of restricted access to their API.

**Comment by cdrappi** [comment]
Uh oh. Good to know this. Very sad!

**Comment by mcdallas** [comment]
I think it's just the api being sluggish just before and during the games. It seems to work fine most of the time.

**Comment by gyerli** [comment]
That's a solid no. It is not sluggish just before and after the games. It is slow almost all the time.

**Comment by mcdallas** [comment]
Well my experience is different. Can they really restrict access to their api though? If you can access it through your browser you can access it with requests.

**Comment by djchie** [comment]
I am experiencing the same issue through [nickb1080's client](https://github.com/nickb1080/nba) for the endpoints as well. I tried making a request directly to the stats.nba API and the same thing happened. It all takes about 8~10 seconds to run.

What's interesting is that if I make a request from Postman rather than localhost, the speed is just fine.

I was wondering if I was running into a DNS lookup issue, so I curled with the following:

`
curl --trace-time -w "time_namelookup:  %{time_namelookup}\ntime_connect:  %{time_connect}\ntime_appconnect:  %{time_appconnect}\ntime_pretransfer:  %{time_pretransfer}\ntime_redirect:  %{time_redirect}\ntime_starttransfer:  %{time_starttransfer}\n----------\ntime_total:  %{time_total}\n" -v http://stats.nba.com/stats/scoreboardV2?DayOffset=0&LeagueID=00&gameDate=12/25/2016
`

And got this as the result:

`
time_namelookup:  0.013
time_connect:  0.038
time_appconnect:  0.000
time_pretransfer:  0.038
time_redirect:  0.000
time_starttransfer:  9.077
----------
time_total:  9.078
`

Both the `time_starttransfer` and the `ttfb` from the Chrome console seems to indicate that it's something on their end?

Also, thought it'd be worth noting, I'm only experiencing this issue with `stats.nba` endpoints, not the ones from `data.nba`, so that might be why @mcdallas's experience is different than @gyerli's?

**Comment by nickb1080** [comment]
I tracked this issue down to the `Connection: keep-alive` header -- after adding that header the issue has entirely disappeared from my [Node.js client](https://github.com/nickb1080/nba). Please give it a try and see if that fixes the issue here!

**Comment by mcdallas** [comment]
@nickb1080 requests sends the keep-alive header by default according to the [docs](http://docs.python-requests.org/en/master/user/advanced/#keep-alive)

**Comment by nickb1080** [comment]
Hmm... guess it must be something else then. FWIW, Node was defaulting to `Connection: close`; adding `keep-alive` seemed to stop the requests from clustering around 10 seconds, and instead they seem to take an amount of time roughly correlated with response time (which was the observed behavior a month or so ago).

**Comment by gyerli** [comment]
I think there no other explanation then they are deliberately slowing down the responses to the requests.

**Comment by nickb1080** [comment]
The question is how are they detecting the difference between programmatic HTTP clients and things like their own website and tools like Postman? And with certain headers I am able to get responses more in the 1-3s range than 8-10s.

**Comment by mcdallas** [comment]
They don't. I tried the site right after I was getting a long response through python and it took 10+ seconds to load the data.

**Comment by seemethere** [comment]
Seems as though they're sending cookie information now:

```
GET /stats/playerdashboardbyyearoveryear?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=202695&PlusMinus=N&Rank=N&Season=2016-17&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&Split=yoy&VsConference=&VsDivision= HTTP/1.1
Host: stats.nba.com
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Referer: http://stats.nba.com/player/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: ug=589ce97107386f0a3c71ba7db7041ee6; ugs=1; _gat=1; s_vi=[CS]v1|2C4E74B9051909B0-4000060EE0004429[CE]; __gads=ID=8589711dd95991d1:T=1486678386:S=ALNI_MZZVfZgBx-Mms92FsbsMJG6Kt4Gpw; _ga=GA1.2.719705049.1486678386; s_cc=true; s_fid=516E3DD519E63EFC-230D8EED429124EF; s_sq=%5B%5BB%5D%5D
```

Taken from the network tab in chrome's developer console while looking at Kawhi Leonard's page
